packages:
  - apps/*
  - packages/*

minimumReleaseAge: 1440

overrides:
  esbuild@<=0.24.2: 0.25.0
  fast-uri@<3.1.6: 3.1.6
  qs@<6.16.0: 6.16.0

allowBuilds:
  argon2: true
  cpu-features: false
  esbuild: true
  protobufjs: false
  simple-git-hooks: true
  ssh2: false
  vue-demi: true
