packages:
  - apps/*
  - packages/*

minimumReleaseAge: 1440

allowBuilds:
  argon2: true
  cpu-features: false
  esbuild: true
  protobufjs: false
  simple-git-hooks: true
  ssh2: false
  vue-demi: true
