CREATE TYPE "public"."export_blob_kind" AS ENUM('audio', 'provider_raw_response');--> statement-breakpoint
CREATE TYPE "public"."export_status" AS ENUM('queued', 'running', 'completed', 'failed', 'invalidated', 'expired');--> statement-breakpoint
CREATE TABLE "journal"."export_blob_lease" (
	"export_id" uuid NOT NULL,
	"entity_id" uuid NOT NULL,
	"blob_kind" "export_blob_kind" NOT NULL,
	"blob_key" text NOT NULL,
	"archive_path" text NOT NULL,
	"media_type" text NOT NULL,
	"byte_size" bigint NOT NULL,
	"sha256" text NOT NULL,
	"lease_expires_at" timestamp with time zone NOT NULL,
	"released_at" timestamp with time zone,
	CONSTRAINT "export_blob_lease_pk" PRIMARY KEY("export_id","blob_key"),
	CONSTRAINT "export_blob_lease_key_not_blank" CHECK (length("journal"."export_blob_lease"."blob_key") > 0),
	CONSTRAINT "export_blob_lease_archive_path_not_blank" CHECK (length("journal"."export_blob_lease"."archive_path") > 0),
	CONSTRAINT "export_blob_lease_byte_size_valid" CHECK ("journal"."export_blob_lease"."byte_size" >= 0),
	CONSTRAINT "export_blob_lease_sha256_valid" CHECK ("journal"."export_blob_lease"."sha256" ~ '^[0-9a-f]{64}$')
);
--> statement-breakpoint
CREATE TABLE "journal"."export_request" (
	"id" uuid PRIMARY KEY NOT NULL,
	"owner_id" uuid NOT NULL,
	"status" "export_status" DEFAULT 'queued' NOT NULL,
	"manifest_schema_version" integer DEFAULT 1 NOT NULL,
	"include_audio" boolean DEFAULT false NOT NULL,
	"include_provider_raw_responses" boolean DEFAULT false NOT NULL,
	"snapshot_at" timestamp with time zone NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"entity_count" integer DEFAULT 0 NOT NULL,
	"file_count" integer DEFAULT 0 NOT NULL,
	"archive_blob_key" text,
	"archive_byte_size" bigint,
	"archive_sha256" text,
	"started_at" timestamp with time zone,
	"completed_at" timestamp with time zone,
	"invalidated_at" timestamp with time zone,
	"error_code" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "export_request_manifest_version_valid" CHECK ("journal"."export_request"."manifest_schema_version" = 1),
	CONSTRAINT "export_request_entity_count_valid" CHECK ("journal"."export_request"."entity_count" >= 0),
	CONSTRAINT "export_request_file_count_valid" CHECK ("journal"."export_request"."file_count" >= 0),
	CONSTRAINT "export_request_archive_sha256_valid" CHECK ("journal"."export_request"."archive_sha256" is null or "journal"."export_request"."archive_sha256" ~ '^[0-9a-f]{64}$')
);
--> statement-breakpoint
CREATE TABLE "journal"."export_snapshot_item" (
	"sequence" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "journal"."export_snapshot_item_sequence_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"export_id" uuid NOT NULL,
	"entity_type" text NOT NULL,
	"stable_id" text NOT NULL,
	"version_id" text,
	"journal_date" date,
	"payload" jsonb NOT NULL,
	CONSTRAINT "export_snapshot_item_type_not_blank" CHECK (length("journal"."export_snapshot_item"."entity_type") > 0),
	CONSTRAINT "export_snapshot_item_stable_id_not_blank" CHECK (length("journal"."export_snapshot_item"."stable_id") > 0)
);
--> statement-breakpoint
ALTER TABLE "journal"."export_blob_lease" ADD CONSTRAINT "export_blob_lease_export_id_export_request_id_fk" FOREIGN KEY ("export_id") REFERENCES "journal"."export_request"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "journal"."export_request" ADD CONSTRAINT "export_request_owner_id_user_id_fk" FOREIGN KEY ("owner_id") REFERENCES "journal"."user"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "journal"."export_snapshot_item" ADD CONSTRAINT "export_snapshot_item_export_id_export_request_id_fk" FOREIGN KEY ("export_id") REFERENCES "journal"."export_request"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "export_blob_lease_entity_idx" ON "journal"."export_blob_lease" USING btree ("entity_id","released_at");--> statement-breakpoint
CREATE INDEX "export_request_owner_created_idx" ON "journal"."export_request" USING btree ("owner_id","created_at","id");--> statement-breakpoint
CREATE INDEX "export_request_expiry_idx" ON "journal"."export_request" USING btree ("status","expires_at");--> statement-breakpoint
CREATE INDEX "export_snapshot_item_stream_idx" ON "journal"."export_snapshot_item" USING btree ("export_id","entity_type","sequence");--> statement-breakpoint
CREATE INDEX "export_snapshot_item_relationship_idx" ON "journal"."export_snapshot_item" USING btree ("export_id","entity_type","stable_id");--> statement-breakpoint
CREATE INDEX "export_snapshot_item_markdown_idx" ON "journal"."export_snapshot_item" USING btree ("export_id","journal_date","sequence");