/** Identifies the owning workspace package without exposing implementation paths. */
export const databasePackageName = '@journal/database' as const;

export {
  createDatabaseClient,
  type CreateDatabaseClientOptions,
  type DatabaseClient,
  type JournalDatabase,
  type JournalTransaction,
  type RepositoryContext,
} from './client.js';
export {
  parseDatabaseCommandEnvironment,
  type ApplicationEnvironment,
  type DatabaseCommandEnvironment,
} from './environment.js';
export { migrateDatabase, migrationsFolder } from './migrations.js';
export {
  artifactApiIdempotency,
  auditEvents,
  authChallenges,
  authenticators,
  contributionRevisions,
  contributions,
  journalDays,
  journalApiIdempotency,
  passwordCredentials,
  processorApiIdempotency,
  processorArtifacts,
  processorArtifactCandidates,
  processorArtifactManualRevisions,
  processorArtifactVersions,
  recoveryCodes,
  recordingApiIdempotency,
  recordingChunks,
  recordings,
  recordingUploads,
  sessions,
  transcriptCleanupRuns,
  transcriptEvidenceSpans,
  transcriptionRuns,
  transcriptRevisions,
  transcriptSegments,
  transcripts,
  users,
  processorInstallations,
  processorReconciliationOutcomes,
  processorReconciliations,
  processorResultEvidence,
  processorResults,
  processorRunInputs,
  processorRuns,
  processorVersionDependencies,
  processorVersions,
  reprocessingApiIdempotency,
  reprocessingBatchItems,
  reprocessingBatches,
} from './schema.js';
export {
  DeletedContributionError,
  JournalReadRepository,
  JournalRecordNotFoundError,
  JournalWriteRepository,
  type ContributionAuditRecord,
  type JournalDaySummaryRecord,
  type JournalMutationAudit,
  type PersistedContribution,
} from './repositories/journal-repository.js';
export {
  FoundationRepository,
  type ProcessorInstallationRecord,
  type QueueConfigurationRecord,
  type ScheduleRecord,
} from './repositories/foundation-repository.js';
export { seedDatabase, type SeedDatabaseResult } from './seeds.js';
export { inTransaction, type TransactionWork } from './transaction.js';
export {
  enqueueProcessorRun,
  invalidateProcessorDependents,
  PROCESSOR_JOB_OPERATION,
  ProcessorRuntimeRepository,
  ProcessorRuntimeStateError,
  type CanonicalProcessorRunInput,
  type ProcessorChangedInput,
  type ProcessorInvalidationResult,
  type ProcessorResultRecord,
  type ProcessorRunRecord,
  type ProcessorRunTarget,
} from './processor-runtime-repository.js';
export {
  reconcileProcessorResult,
  ProcessorReconciliationStateError,
  type PersistedProcessorReconciliation,
  type ProcessorReconciliationOutcomeRecord,
  type ProcessorReconciliationRecord,
} from './processor-reconciliation-repository.js';
export {
  enqueueTranscriptionRun,
  TRANSCRIPTION_JOB_OPERATION,
  TranscriptionRepository,
  TranscriptionStateError,
  type CanonicalTranscriptionInput,
  type PersistedSpeechContextItem,
  type PersistedTranscriptionSuccess,
  type TranscriptionRecordingRecord,
  type TranscriptionRunRecord,
} from './transcription-repository.js';
export {
  appendCorrectedTranscriptRevision,
  enqueueTranscriptCleanup,
  TRANSCRIPT_CLEANUP_JOB_OPERATION,
  TranscriptCleanupRepository,
  TranscriptCleanupStateError,
  TranscriptRevisionConflictError,
  type CanonicalTranscriptCleanupInput,
  type CleanupPromptSnapshot,
  type PersistedTranscriptCleanupSuccess,
  type TranscriptCleanupRunRecord,
  type TranscriptRecord,
  type TranscriptRevisionRecord,
} from './transcript-cleanup-repository.js';
export {
  canonicalTranscriptEvidenceText,
  evidenceQuoteHash,
  invalidateTranscriptRevisionDependents,
  persistTranscriptSegments,
  TranscriptEvidenceRepository,
  TranscriptEvidenceStateError,
  type PersistableTranscriptSegment,
  type TranscriptEvidenceSpanRecord,
  type TranscriptInvalidationResult,
  type TranscriptSegmentRecord,
} from './transcript-evidence-repository.js';
export {
  allQueueDefinitions,
  createJobFingerprint,
  createQueueJobPayload,
  EXPECTED_PG_BOSS_SCHEMA_VERSION,
  InvalidQueuePayloadError,
  parseQueueJobPayload,
  QUEUE_PAYLOAD_SCHEMA_VERSION,
  queueDefinitions,
  queueNames,
  type QueueDefinition,
  type QueueJobPayload,
  type QueueName,
} from './queue-contracts.js';
export {
  assertQueueFoundation,
  cancelQueueJob,
  classifyQueueError,
  createQueueClient,
  enqueueJobInTransaction,
  provisionQueueFoundation,
  QueueFoundationError,
  QueueJobError,
  registerQueueWorker,
  type CanonicalJobHandler,
  type CanonicalJobInput,
  type QueueAttemptDisposition,
} from './queue-runtime.js';
